/**id_carrito     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     VARCHAR2(36),
    id_producto    VARCHAR2(36) NOT NULL,
    cantidad       NUMBER       NOT NULL,
    fecha_agregado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, */

export interface Carrito {
  idCarrito: number; // ID del carrito, generado automáticamente
  idUsuario: string; // ID del usuario propietario del carrito
  idProducto: string; // ID del producto en el carrito
  cantidad: number; // Cantidad del producto en el carrito
  fechaAgregado: string; // Fecha y hora en que se agregó el producto al carrito
}